id: PF4741F55
initial_creation_type: ocr
source_metadata:
  id: bdr:W686
  title: དུས་འཁོར་སྤྱི་དོན་དྲི་མེད་འོད་རྒྱན
  volumes:
    6dc8579e19c14cd3af070471655afd96:
      image_group_id: I1PD36371
      title: ''
      base_file: v001.txt
  author: ''
